language: python
branches:
  only:
    - master
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.5
      env: TOXENV=py35
    - python: 3.3
      env: TOXENV=py33
install:
  - pip install tox
script:
  - tox

